### ISSUE TITLE
No iBoot version found! 

### ISSUE THREAD

**Issue by matteyeux** [iH8sn0w/iBoot32Patcher#2]
Here is the issue, this time I'm using a decrypted iPhone5,4 kernelcache (9.3.5)

```
$ ./iBoot32Patcher iBoot.n49.RELEASE.img3.dec iBoot.n49.RELEASE.img3.patch -b "cs_enforcement_disable=1" -c "ticket" 0x80000000
main: Starting...
main: No iBoot version found!
```

**Comment by h3adshotzz** [comment]
Also getting this issue with iPhone5,1 10.0.2 & 10.1

**Comment by iH8sn0w** [comment]
@matteyeux @h3adshotzz If I had to guess, I'd say the image is decrypted but still in an img3 container?

**Comment by matteyeux** [comment]
@iH8sn0w So we have  to dd it out of the container ?

**Comment by iH8sn0w** [comment]
@matteyeux planetbeing's xpwntool does it automatically (unless the -decrypt flag is present). I pushed eaad0459af73ddc268700ab4420127293b7dd583 to provide additional feedback.

**Comment by matteyeux** [comment]
Ay thanks for explaining
